name: Azure DevOps Pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore ./src/SoftwareTesting.sln
    displayName: 'Restore dependencies'

  - script: dotnet build ./src/SoftwareTesting.sln --no-restore
    displayName: 'Build'

  - script: |
      pwsh /home/runner/work/SoftwareTestingQA/SoftwareTestingQA/src/PlaywrightTests/bin/Debug/net6.0/playwright.ps1 install --with-deps
    displayName: 'Browser install'

  - script: |
      dotnet test ./src/PlaywrightTests/PlaywrightTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=newplaywrighttest.trx"
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '/home/runner/work/SoftwareTestingQA/SoftwareTestingQA/src/PlaywrightTests/TestResults/newplaywrighttest.trx'
      mergeTestResults: true
    condition: always()
    displayName: 'Publish Test Results'